from .model import LessonEntry, topic_entry

CHAPTER = "第2章 矩阵的诞生——向量的批处理"

TOPICS: tuple[LessonEntry, ...] = (
    topic_entry(topic_id="ch02.batch.inner-products", chapter_number=2, section_id="ch02.s22", title="批量内积与多角度比较", source_path=(CHAPTER, "2.2 批量内积", "批量内积的几何解释"), heading_path=(CHAPTER, "2.2 批量内积"), heading_level=3, required_capabilities=("vector_2d", "batch_inner_product")),
    topic_entry(topic_id="ch02.batch.projection", chapter_number=2, section_id="ch02.s23", title="投影矩阵把一批向量压到方向上", source_path=(CHAPTER, "2.3 批量投影", "投影矩阵的几何解释"), heading_path=(CHAPTER, "2.3 批量投影"), heading_level=3, required_capabilities=("projection_2d", "transformed_grid")),
    topic_entry(topic_id="ch02.matrix.additive-distributivity", chapter_number=2, section_id="ch02.s24", title="矩阵加法与变换分配律", source_path=(CHAPTER, "2.4 矩阵加法与矩阵数乘", "分配律的几何解释"), heading_path=(CHAPTER, "2.4 矩阵加法与矩阵数乘"), heading_level=3, required_capabilities=("staged_transform", "vector_2d")),
    topic_entry(topic_id="ch02.matrix.row-column", chapter_number=2, section_id="ch02.s25", title="矩阵乘向量的行视角与列视角", source_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.1 两种算法"), heading_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.1 两种算法"), heading_level=4, required_capabilities=("vector_2d",)),
    topic_entry(topic_id="ch02.matrix.transformed-grid", chapter_number=2, section_id="ch02.s25", title="基向量变换与网格变形", source_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.2 核心几何理解"), heading_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.2 核心几何理解"), heading_level=4, required_capabilities=("transformed_grid", "vector_2d")),
    topic_entry(topic_id="ch02.matrix.stretch-rotate-scale", chapter_number=2, section_id="ch02.s25", title="拉伸、旋转与缩放的矩阵图像", source_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.3 分层例题"), heading_path=(CHAPTER, "2.5 矩阵 $\\times$ 向量（核心节）", "2.5.3 分层例题"), heading_level=4, required_capabilities=("transformed_grid", "staged_transform")),
    topic_entry(topic_id="ch02.matrix.composition", chapter_number=2, section_id="ch02.s26", title="复合变换与 AB ≠ BA", source_path=(CHAPTER, "2.6 矩阵 $\\times$ 矩阵", "复合变换与 AB ≠ BA"), heading_path=(CHAPTER, "2.6 矩阵 $\\times$ 矩阵"), heading_level=3, required_capabilities=("staged_transform", "transformed_grid")),
    topic_entry(topic_id="ch02.matrix.basis", chapter_number=2, section_id="ch02.s27", title="矩阵的列与新基坐标", source_path=(CHAPTER, "2.7 矩阵与基", "换基改变坐标描述"), heading_path=(CHAPTER, "2.7 矩阵与基"), heading_level=3, required_capabilities=("vector_2d", "annotation_formula")),
    topic_entry(topic_id="ch02.matrix.powers", chapter_number=2, section_id="ch02.s28", title="矩阵幂表示重复变换", source_path=(CHAPTER, "2.8 矩阵的幂与转置的性质", "矩阵幂的几何意义"), heading_path=(CHAPTER, "2.8 矩阵的幂与转置的性质"), heading_level=2, required_capabilities=("staged_transform", "transformed_grid")),
    topic_entry(topic_id="ch02.subspace.independence", chapter_number=2, section_id="ch02.s29", title="线性无关与线性相关的方向图", source_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.1 线性无关与线性相关"), heading_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.1 线性无关与线性相关"), heading_level=4, required_capabilities=("vector_2d", "subspace_region")),
    topic_entry(topic_id="ch02.subspace.rank", chapter_number=2, section_id="ch02.s29", title="秩与输出空间的真实维度", source_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.2 秩"), heading_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.2 秩"), heading_level=4, required_capabilities=("subspace_region", "transformed_grid")),
    topic_entry(topic_id="ch02.subspace.null", chapter_number=2, section_id="ch02.s29", title="零空间是被压到原点的方向", source_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.3 零空间"), heading_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.3 零空间"), heading_level=4, required_capabilities=("subspace_region", "staged_transform")),
    topic_entry(topic_id="ch02.subspace.column", chapter_number=2, section_id="ch02.s29", title="列空间是变换可到达的位置", source_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.4 列空间"), heading_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.4 列空间"), heading_level=4, required_capabilities=("subspace_region", "vector_2d")),
    topic_entry(topic_id="ch02.subspace.rank-nullity", chapter_number=2, section_id="ch02.s29", title="秩-零化度的维数守恒", source_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.5 与后续章节的关系"), heading_path=(CHAPTER, "2.9 秩、零空间与列空间（为第4章准备的代数工具）", "2.9.5 与后续章节的关系"), heading_level=4, required_capabilities=("subspace_region", "annotation_formula")),
    topic_entry(topic_id="ch02.high-dimensional.analogy", chapter_number=2, section_id="ch02.s210", title="n 维矩阵运算的低维类比", source_path=(CHAPTER, "2.10 高维拓展：n维空间中的矩阵运算", "n维矩阵运算的几何类比"), heading_path=(CHAPTER, "2.10 高维拓展：n维空间中的矩阵运算"), heading_level=2, required_capabilities=("transformed_grid", "subspace_region", "annotation_formula")),
)
